
package sd.clt.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileServerImplWS", targetNamespace = "http://srv.tp1.sd/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileServerImplWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     * @throws InfoNotFoundException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFile", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.clt.ws.GetFile")
    @ResponseWrapper(localName = "getFileResponse", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.clt.ws.GetFileResponse")
    @Action(input = "http://srv.tp1.sd/FileServerImplWS/getFileRequest", output = "http://srv.tp1.sd/FileServerImplWS/getFileResponse", fault = {
        @FaultAction(className = InfoNotFoundException_Exception.class, value = "http://srv.tp1.sd/FileServerImplWS/getFile/Fault/InfoNotFoundException"),
        @FaultAction(className = IOException_Exception.class, value = "http://srv.tp1.sd/FileServerImplWS/getFile/Fault/IOException")
    })
    public byte[] getFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception, InfoNotFoundException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws InfoNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAlbumList", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.clt.ws.GetAlbumList")
    @ResponseWrapper(localName = "getAlbumListResponse", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.clt.ws.GetAlbumListResponse")
    @Action(input = "http://srv.tp1.sd/FileServerImplWS/getAlbumListRequest", output = "http://srv.tp1.sd/FileServerImplWS/getAlbumListResponse", fault = {
        @FaultAction(className = InfoNotFoundException_Exception.class, value = "http://srv.tp1.sd/FileServerImplWS/getAlbumList/Fault/InfoNotFoundException")
    })
    public List<String> getAlbumList()
        throws InfoNotFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns sd.tp1.clt.ws.FileInfo
     * @throws InfoNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFileInfo", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.clt.ws.GetFileInfo")
    @ResponseWrapper(localName = "getFileInfoResponse", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.clt.ws.GetFileInfoResponse")
    @Action(input = "http://srv.tp1.sd/FileServerImplWS/getFileInfoRequest", output = "http://srv.tp1.sd/FileServerImplWS/getFileInfoResponse", fault = {
        @FaultAction(className = InfoNotFoundException_Exception.class, value = "http://srv.tp1.sd/FileServerImplWS/getFileInfo/Fault/InfoNotFoundException")
    })
    public FileInfo getFileInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws InfoNotFoundException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws InfoNotFoundException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "uploadFile", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.clt.ws.UploadFile")
    @ResponseWrapper(localName = "uploadFileResponse", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.clt.ws.UploadFileResponse")
    @Action(input = "http://srv.tp1.sd/FileServerImplWS/uploadFileRequest", output = "http://srv.tp1.sd/FileServerImplWS/uploadFileResponse", fault = {
        @FaultAction(className = InfoNotFoundException_Exception.class, value = "http://srv.tp1.sd/FileServerImplWS/uploadFile/Fault/InfoNotFoundException"),
        @FaultAction(className = IOException_Exception.class, value = "http://srv.tp1.sd/FileServerImplWS/uploadFile/Fault/IOException")
    })
    public void uploadFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1)
        throws IOException_Exception, InfoNotFoundException_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "alive", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.clt.ws.Alive")
    @ResponseWrapper(localName = "aliveResponse", targetNamespace = "http://srv.tp1.sd/", className = "sd.tp1.clt.ws.AliveResponse")
    @Action(input = "http://srv.tp1.sd/FileServerImplWS/aliveRequest", output = "http://srv.tp1.sd/FileServerImplWS/aliveResponse")
    public void alive(
        @WebParam(name = "arg0", targetNamespace = "")
        boolean arg0);

}
